version: '{build}'

branches:
  only:
  - master
  - /ci.*/
  - /stable.*/

init:
- ps: $env:commit = $env:appveyor_repo_commit.SubString(0,8)

install:
- ps: Install-Product node $env:NODE_VERSION
- ps: npm config set msvs_version 2013

# Extract the codesigning certs, encrypted private ssh key
- ps: |
    C:\OpenSSL-Win32\bin\openssl.exe aes-256-cbc -K $env:encrypted_faf2708e46e2_key -iv $env:encrypted_faf2708e46e2_iv -in app/build/resources/certs.tar.enc -out app/build/resources/certs.tar -d;
    mkdir app/build/resources/certs;
    tar xvf app/build/resources/certs.tar --directory=app/build/resources/;

# Clone the submodule
- ps: |
    $env:GIT_SSH_COMMAND="ssh -i app/build/resources/certs/mailsync-deploy-key -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no";
    git submodule update --init mailsync

build_script:
- cmd: cd .\mailsync && .\build.cmd && cd ..\
- cmd: npm install && npm run build
- cmd: node app/build/create-signed-windows-installer.js

before_deploy:
  - ps: Get-ChildItem .\app\dist\*.exe | % { Push-AppveyorArtifact $_.FullName -FileName "win-ia32/$($_.Name)" -DeploymentName s3-deployment }
  - ps: Get-ChildItem .\app\dist\*.nupkg | % { Push-AppveyorArtifact $_.FullName -FileName "win-ia32/$($_.Name)" -DeploymentName s3-deployment }
  - ps: Get-ChildItem .\app\dist\RELEASES | % { Push-AppveyorArtifact $_.FullName -FileName "win-ia32/$($_.Name)" -DeploymentName s3-deployment }

deploy:
- provider: S3
  name: s3-deployment
  access_key_id: AKIAJQWOM4SPSY3TXI5Q
  secret_access_key:
    secure: XlLzz7sdvrtgi4g459NvxLfrH/+hOutb+0Osz29unfi4Zcw9N8H8SEaq6m3ZeWc+
  region: us-east-1
  bucket: merani-builds
  folder: "client/$(commit)"
  set_public: true
 
environment:
  matrix:
  - NODE_VERSION: 7.10
  global:
    SIGN_BUILD: true
    CERTIFICATE_FILE: .\app\build\resources\certs\appveyor\win-nylas-n1.p12
    encrypted_faf2708e46e2_key:
      secure: mdegN/AldrADhtEop6mDwq6d4jUskzijK2X7Twf2lj9t3jdaW4OtMuJ5Ywyt+GN/N7qMFr7LOvxQ5gz4aoIW+Dg9d03AX3BH1o4BI6g+wdk=
    encrypted_faf2708e46e2_iv:
      secure: B2pwd1AlmQHjIpIau1NylfEMkwJJ5u7NhxgZcU8WicwP6+cmePnAacYIwpe1fXEf

cache:
  - node_modules -> package.json
  - app\node_modules -> app\package.json
  - '%USERPROFILE%\.npm'
