# The private Nylas monorepo build script. This will build a full signed
# release for the Nylas Mail client
sudo: false

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - build-essential
    - clang
    - fakeroot
    - g++-4.8
    - git
    - libgnome-keyring-dev
    - xvfb
    - rpm
    - libxext-dev
    - libxtst-dev
    - libxkbfile-dev

branches:
  only:
  - master
  - /ci-.*/
  - /stable.*/

matrix:
  include:
  - os: linux
    env: NODE_VERSION=6.9 CC=gcc-4.8 CXX=g++-4.8 DEBUG="electron-packager:*" ONLY_CLIENT=true
  - os: osx
    env: NODE_VERSION=6.9 CC=clang CXX=clang++ SIGN_BUILD=true DEBUG="electron-packager:*" ONLY_CLIENT=true

before_install:
- openssl aes-256-cbc
  -K $encrypted_faf2708e46e2_key
  -iv $encrypted_faf2708e46e2_iv
  -in packages/client-private-plugins/encrypted_certificates/travis/travis-files.tar.enc
  -out packages/client-private-plugins/encrypted_certificates/travis/travis-files.tar
  -d;
- mkdir packages/client-app/build/resources/certs;
- tar xvf packages/client-private-plugins/encrypted_certificates/travis/travis-files.tar
  --directory=packages/client-app/build/resources/;
- source packages/client-app/build/resources/certs/mac/set_unix_env.sh;

install:
- git clone https://github.com/creationix/nvm.git /tmp/.nvm
- source /tmp/.nvm/nvm.sh
- nvm install $NODE_VERSION
- nvm use --delete-prefix $NODE_VERSION

script:
- npm install && npm run build-client && npm run upload-client

cache:
  directories:
  - node_modules
  - apm/node_modules
