env:
  global:
    - NYLAS_ACCESS_TOKEN=cb200be7c921f73a1c35930f6a4ac8758b271be0

sudo: required
dist: trusty

matrix:
  include:
    - os: linux
      env: NODE_VERSION=0.10
    - os: linux
      env: NODE_VERSION=0.12
# Trusty image already has a few Node.js versions preinstalled,
# including 0.10, 0.12, and 4.1, but not 4.2 and 5. Explicitly
# denote installation of these versions
    - os: linux
      env: NODE_VERSION=4.2 NODE_INSTALL=1
    - os: linux
      env: NODE_VERSION=5 NODE_INSTALL=1
    - os: osx
      env: NODE_VERSION=0.10
    - os: osx
      env: NODE_VERSION=0.12 CC=clang CXX=clang++
    - os: osx
      env: NODE_VERSION=4.2 CC=clang CXX=clang++
    - os: osx
      env: NODE_VERSION=5 CC=clang CXX=clang++

install:
  - if [ "${TRAVIS_OS_NAME}" == "osx" ]; then
    git clone https://github.com/creationix/nvm.git /tmp/.nvm;
    source /tmp/.nvm/nvm.sh;
    nvm install $NODE_VERSION;
    fi
  - if [ "${NODE_INSTALL}" == "1" ]; then
    nvm install $NODE_VERSION;
    fi
  - nvm use --delete-prefix $NODE_VERSION

before_script:
  - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then
    export DISPLAY=:99.0;
    sh -e /etc/init.d/xvfb start;
    fi

script: script/cibuild

addons:
  apt:
    packages:
    - fakeroot
    - libgnome-keyring-dev

git:
  submodules: false
