version: '{build}'

platform:
  - x86

pull_requests:
  do_not_increment_build_number: true

branches:
  only:
  - master
  - ci-test
  - stable
  - /ci-build\/.*/
  - n1-next

# We need to only clone the main module because our submodule requires the
# encrypted ssh key to access submodules
clone_depth: 1
build:
  verbosity: minimal
install:
- ps: Install-Product node $env:NODE_VERSION $env:PLATFORM
- ps: nuget install secure-file -ExcludeVersion
- ps: npm config set msvs_version 2013

# We need to extract the encrypted private ssh key to clone the submodule.
- ps: |
    if ($env:DECRYPTION_PASSWORD) {
      secure-file\tools\secure-file -decrypt build\resources\ssh\nylas-n1-ci-ssh-secure-file.enc -secret $env:DECRYPTION_PASSWORD
      mv -Force build\resources\ssh\nylas-n1-ci-ssh-secure-file c:\users\appveyor\.ssh\id_rsa

      # http://stackoverflow.com/questions/21002919/running-a-remote-powershell-script-with-a-git-command-in-it-results-in-nativecom
      Start-Process -FilePath git.exe -ArgumentList 'submodule update --init --recursive'  -Wait -NoNewWindow

      secure-file\tools\secure-file -decrypt src\K2\packages\local-private\encrypted_certificates\appveyor\win-nylas-n1.p12.enc -secret $env:DECRYPTION_PASSWORD
      secure-file\tools\secure-file -decrypt src\K2\packages\local-private\encrypted_certificates\appveyor\set_win_env.ps1.enc -secret $env:DECRYPTION_PASSWORD
      . src\K2\packages\local-private\encrypted_certificates\appveyor\set_win_env.ps1
    }

build_script:
- cmd: script\bootstrap.cmd

deploy_script:
- cmd: script\grunt.cmd ci --stack --no-color

environment:
  matrix:
  - NODE_VERSION: 6.9
    PUBLISH_BUILD: true
  global:
    CERTIFICATE_FILE: .\src\K2\packages\local-private\encrypted_certificates\appveyor\win-nylas-n1.p12
    DECRYPTION_PASSWORD:
      secure: 48VSzDtdBd52Xlo3TZ1NeR1yRRrZ3AU6Px5XjD5RDp44cFU5GYVspecGqX6DGCV7i0D7nldGMyEbXNrjM1t1Kw==

cache:
  - apm\node_modules -> apm\package.json
  - build\node_modules -> build\package.json
  - '%USERPROFILE%\.nylas\.apm'
  - '%USERPROFILE%\.npm'
